export const seatingMockData = [
  {
    "room": 1,
    "rows": {
      "1": [
        { "idx": 0, "col": "a", "sold": false },
        { "idx": 1, "col": "b", "sold": false },
        { "idx": 2, "col": "c", "sold": false },
        { "idx": 3, "col": "d", "sold": false },
        { "idx": 4, "col": "e", "sold": false },
        { "idx": 5, "col": "f", "sold": false },
        { "idx": 6, "col": "g", "sold": false },
        { "idx": 7, "col": "h", "sold": false },
        { "idx": 8, "col": "i", "sold": false },
        { "idx": 9, "col": "j", "sold": false },
        { "idx": 10, "col": "k", "sold": false },
        { "idx": 11, "col": "l", "sold": false }
      ],
      "2": [
        { "idx": 0, "col": "a", "sold": false },
        { "idx": 1, "col": "b", "sold": false },
        { "idx": 2, "col": "c", "sold": false },
        { "idx": 3, "col": "d", "sold": false },
        { "idx": 4, "col": "e", "sold": false },
        { "idx": 5, "col": "f", "sold": false },
        { "idx": 6, "col": "g", "sold": false },
        { "idx": 7, "col": "h", "sold": false },
        { "idx": 8, "col": "i", "sold": false },
        { "idx": 9, "col": "j", "sold": false },
        { "idx": 10, "col": "k", "sold": false },
        { "idx": 11, "col": "l", "sold": false }
      ],
      "3": [
        { "idx": 0, "col": "a", "sold": false },
        { "idx": 1, "col": "b", "sold": false },
        { "idx": 2, "col": "c", "sold": false },
        { "idx": 3, "col": "d", "sold": false },
        { "idx": 4, "col": "e", "sold": false },
        { "idx": 5, "col": "f", "sold": false },
        { "idx": 6, "col": "g", "sold": false },
        { "idx": 7, "col": "h", "sold": false },
        { "idx": 8, "col": "i", "sold": false },
        { "idx": 9, "col": "j", "sold": false },
        { "idx": 10, "col": "k", "sold": false },
        { "idx": 11, "col": "l", "sold": false }
      ],
      "4": [
        { "idx": 0, "col": "a", "sold": false },
        { "idx": 1, "col": "b", "sold": false },
        { "idx": 2, "col": "c", "sold": false },
        { "idx": 3, "col": "d", "sold": false },
        { "idx": 4, "col": "e", "sold": false },
        { "idx": 5, "col": "f", "sold": false },
        { "idx": 6, "col": "g", "sold": false },
        { "idx": 7, "col": "h", "sold": false },
        { "idx": 8, "col": "i", "sold": false },
        { "idx": 9, "col": "j", "sold": false },
        { "idx": 10, "col": "k", "sold": false },
        { "idx": 11, "col": "l", "sold": false }
      ],
      "5": [
        { "idx": 0, "col": "a", "sold": false },
        { "idx": 1, "col": "b", "sold": false },
        { "idx": 2, "col": "c", "sold": false },
        { "idx": 3, "col": "d", "sold": false },
        { "idx": 4, "col": "e", "sold": false },
        { "idx": 5, "col": "f", "sold": false },
        { "idx": 6, "col": "g", "sold": false },
        { "idx": 7, "col": "h", "sold": false },
        { "idx": 8, "col": "i", "sold": false },
        { "idx": 9, "col": "j", "sold": false },
        { "idx": 10, "col": "k", "sold": false },
        { "idx": 11, "col": "l", "sold": false }
      ],
      "6": [
        { "idx": 0, "col": "a", "sold": false },
        { "idx": 1, "col": "b", "sold": false },
        { "idx": 2, "col": "c", "sold": false },
        { "idx": 3, "col": "d", "sold": false },
        { "idx": 4, "col": "e", "sold": false },
        { "idx": 5, "col": "f", "sold": false },
        { "idx": 6, "col": "g", "sold": false },
        { "idx": 7, "col": "h", "sold": false },
        { "idx": 8, "col": "i", "sold": false },
        { "idx": 9, "col": "j", "sold": false },
        { "idx": 10, "col": "k", "sold": false },
        { "idx": 11, "col": "l", "sold": false }
      ],
      "7": [
        { "idx": 0, "col": "a", "sold": false },
        { "idx": 1, "col": "b", "sold": false },
        { "idx": 2, "col": "c", "sold": false },
        { "idx": 3, "col": "d", "sold": false },
        { "idx": 4, "col": "e", "sold": false },
        { "idx": 5, "col": "f", "sold": false },
        { "idx": 6, "col": "g", "sold": false },
        { "idx": 7, "col": "h", "sold": false },
        { "idx": 8, "col": "i", "sold": false },
        { "idx": 9, "col": "j", "sold": false },
        { "idx": 10, "col": "k", "sold": false },
        { "idx": 11, "col": "l", "sold": false }
      ],
      "8": [
        { "idx": 0, "col": "a", "sold": false },
        { "idx": 1, "col": "b", "sold": false },
        { "idx": 2, "col": "c", "sold": false },
        { "idx": 3, "col": "d", "sold": false },
        { "idx": 4, "col": "e", "sold": false },
        { "idx": 5, "col": "f", "sold": false },
        { "idx": 6, "col": "g", "sold": false },
        { "idx": 7, "col": "h", "sold": false },
        { "idx": 8, "col": "i", "sold": false },
        { "idx": 9, "col": "j", "sold": false },
        { "idx": 10, "col": "k", "sold": false },
        { "idx": 11, "col": "l", "sold": false }
      ],
      "9": [
        { "idx": 0, "col": "a", "sold": false },
        { "idx": 1, "col": "b", "sold": false },
        { "idx": 2, "col": "c", "sold": false },
        { "idx": 3, "col": "d", "sold": false },
        { "idx": 4, "col": "e", "sold": false },
        { "idx": 5, "col": "f", "sold": false },
        { "idx": 6, "col": "g", "sold": false },
        { "idx": 7, "col": "h", "sold": false },
        { "idx": 8, "col": "i", "sold": false },
        { "idx": 9, "col": "j", "sold": false },
        { "idx": 10, "col": "k", "sold": false },
        { "idx": 11, "col": "l", "sold": false }
      ]
    }
  },
  {
    "room": 2,
    "rows": {
      "1": [
        { "idx": 0, "col": "a", "sold": false },
        { "idx": 1, "col": "b", "sold": false },
        { "idx": 2, "col": "c", "sold": false },
        { "idx": 3, "col": "d", "sold": false },
        { "idx": 4, "col": "e", "sold": false },
        { "idx": 5, "col": "f", "sold": false },
        { "idx": 6, "col": "g", "sold": false },
        { "idx": 7, "col": "h", "sold": false },
        { "idx": 8, "col": "i", "sold": false },
        { "idx": 9, "col": "j", "sold": false },
        { "idx": 10, "col": "k", "sold": false },
        { "idx": 11, "col": "l", "sold": false }
      ],
      "2": [
        { "idx": 0, "col": "a", "sold": false },
        { "idx": 1, "col": "b", "sold": false },
        { "idx": 2, "col": "c", "sold": false },
        { "idx": 3, "col": "d", "sold": false },
        { "idx": 4, "col": "e", "sold": false },
        { "idx": 5, "col": "f", "sold": false },
        { "idx": 6, "col": "g", "sold": false },
        { "idx": 7, "col": "h", "sold": false },
        { "idx": 8, "col": "i", "sold": false },
        { "idx": 9, "col": "j", "sold": false },
        { "idx": 10, "col": "k", "sold": false },
        { "idx": 11, "col": "l", "sold": false }
      ],
      "3": [
        { "idx": 0, "col": "a", "sold": false },
        { "idx": 1, "col": "b", "sold": false },
        { "idx": 2, "col": "c", "sold": false },
        { "idx": 3, "col": "d", "sold": false },
        { "idx": 4, "col": "e", "sold": false },
        { "idx": 5, "col": "f", "sold": false },
        { "idx": 6, "col": "g", "sold": false },
        { "idx": 7, "col": "h", "sold": false },
        { "idx": 8, "col": "i", "sold": false },
        { "idx": 9, "col": "j", "sold": false },
        { "idx": 10, "col": "k", "sold": false },
        { "idx": 11, "col": "l", "sold": false }
      ],
      "4": [
        { "idx": 0, "col": "a", "sold": false },
        { "idx": 1, "col": "b", "sold": false },
        { "idx": 2, "col": "c", "sold": false },
        { "idx": 3, "col": "d", "sold": false },
        { "idx": 4, "col": "e", "sold": false },
        { "idx": 5, "col": "f", "sold": false },
        { "idx": 6, "col": "g", "sold": false },
        { "idx": 7, "col": "h", "sold": false },
        { "idx": 8, "col": "i", "sold": false },
        { "idx": 9, "col": "j", "sold": false },
        { "idx": 10, "col": "k", "sold": false },
        { "idx": 11, "col": "l", "sold": false }
      ],
      "5": [
        { "idx": 0, "col": "a", "sold": false },
        { "idx": 1, "col": "b", "sold": false },
        { "idx": 2, "col": "c", "sold": false },
        { "idx": 3, "col": "d", "sold": false },
        { "idx": 4, "col": "e", "sold": false },
        { "idx": 5, "col": "f", "sold": false },
        { "idx": 6, "col": "g", "sold": false },
        { "idx": 7, "col": "h", "sold": false },
        { "idx": 8, "col": "i", "sold": false },
        { "idx": 9, "col": "j", "sold": false },
        { "idx": 10, "col": "k", "sold": false },
        { "idx": 11, "col": "l", "sold": false }
      ],
      "6": [
        { "idx": 0, "col": "a", "sold": false },
        { "idx": 1, "col": "b", "sold": false },
        { "idx": 2, "col": "c", "sold": false },
        { "idx": 3, "col": "d", "sold": false },
        { "idx": 4, "col": "e", "sold": false },
        { "idx": 5, "col": "f", "sold": false },
        { "idx": 6, "col": "g", "sold": false },
        { "idx": 7, "col": "h", "sold": false },
        { "idx": 8, "col": "i", "sold": false },
        { "idx": 9, "col": "j", "sold": false },
        { "idx": 10, "col": "k", "sold": false },
        { "idx": 11, "col": "l", "sold": false }
      ],
      "7": [
        { "idx": 0, "col": "a", "sold": false },
        { "idx": 1, "col": "b", "sold": false },
        { "idx": 2, "col": "c", "sold": false },
        { "idx": 3, "col": "d", "sold": false },
        { "idx": 4, "col": "e", "sold": false },
        { "idx": 5, "col": "f", "sold": false },
        { "idx": 6, "col": "g", "sold": false },
        { "idx": 7, "col": "h", "sold": false },
        { "idx": 8, "col": "i", "sold": false },
        { "idx": 9, "col": "j", "sold": false },
        { "idx": 10, "col": "k", "sold": false },
        { "idx": 11, "col": "l", "sold": false }
      ],
      "8": [
        { "idx": 0, "col": "a", "sold": false },
        { "idx": 1, "col": "b", "sold": false },
        { "idx": 2, "col": "c", "sold": false },
        { "idx": 3, "col": "d", "sold": false },
        { "idx": 4, "col": "e", "sold": false },
        { "idx": 5, "col": "f", "sold": false },
        { "idx": 6, "col": "g", "sold": false },
        { "idx": 7, "col": "h", "sold": false },
        { "idx": 8, "col": "i", "sold": false },
        { "idx": 9, "col": "j", "sold": false },
        { "idx": 10, "col": "k", "sold": false },
        { "idx": 11, "col": "l", "sold": false }
      ]
    }
  },
  {
    "room": 3,
    "rows": {
      "1": [
        { "idx": 0, "col": "a", "sold": false },
        { "idx": 1, "col": "b", "sold": false },
        { "idx": 2, "col": "c", "sold": false },
        { "idx": 3, "col": "d", "sold": false },
        { "idx": 4, "col": "e", "sold": false },
        { "idx": 5, "col": "f", "sold": false },
        { "idx": 6, "col": "g", "sold": false },
        { "idx": 7, "col": "h", "sold": false },
        { "idx": 8, "col": "i", "sold": false },
        { "idx": 9, "col": "j", "sold": false },
        { "idx": 10, "col": "k", "sold": false },
        { "idx": 11, "col": "l", "sold": false }
      ],
      "2": [
        { "idx": 0, "col": "a", "sold": false },
        { "idx": 1, "col": "b", "sold": false },
        { "idx": 2, "col": "c", "sold": false },
        { "idx": 3, "col": "d", "sold": false },
        { "idx": 4, "col": "e", "sold": false },
        { "idx": 5, "col": "f", "sold": false },
        { "idx": 6, "col": "g", "sold": false },
        { "idx": 7, "col": "h", "sold": false },
        { "idx": 8, "col": "i", "sold": false },
        { "idx": 9, "col": "j", "sold": false },
        { "idx": 10, "col": "k", "sold": false },
        { "idx": 11, "col": "l", "sold": false }
      ],
      "3": [
        { "idx": 0, "col": "a", "sold": false },
        { "idx": 1, "col": "b", "sold": false },
        { "idx": 2, "col": "c", "sold": false },
        { "idx": 3, "col": "d", "sold": false },
        { "idx": 4, "col": "e", "sold": false },
        { "idx": 5, "col": "f", "sold": false },
        { "idx": 6, "col": "g", "sold": false },
        { "idx": 7, "col": "h", "sold": false },
        { "idx": 8, "col": "i", "sold": false },
        { "idx": 9, "col": "j", "sold": false },
        { "idx": 10, "col": "k", "sold": false },
        { "idx": 11, "col": "l", "sold": false }
      ],
      "4": [
        { "idx": 0, "col": "a", "sold": false },
        { "idx": 1, "col": "b", "sold": false },
        { "idx": 2, "col": "c", "sold": false },
        { "idx": 3, "col": "d", "sold": false },
        { "idx": 4, "col": "e", "sold": false },
        { "idx": 5, "col": "f", "sold": false },
        { "idx": 6, "col": "g", "sold": false },
        { "idx": 7, "col": "h", "sold": false },
        { "idx": 8, "col": "i", "sold": false },
        { "idx": 9, "col": "j", "sold": false },
        { "idx": 10, "col": "k", "sold": false },
        { "idx": 11, "col": "l", "sold": false }
      ],
      "5": [
        { "idx": 0, "col": "a", "sold": false },
        { "idx": 1, "col": "b", "sold": false },
        { "idx": 2, "col": "c", "sold": false },
        { "idx": 3, "col": "d", "sold": false },
        { "idx": 4, "col": "e", "sold": false },
        { "idx": 5, "col": "f", "sold": false },
        { "idx": 6, "col": "g", "sold": false },
        { "idx": 7, "col": "h", "sold": false },
        { "idx": 8, "col": "i", "sold": false },
        { "idx": 9, "col": "j", "sold": false },
        { "idx": 10, "col": "k", "sold": false },
        { "idx": 11, "col": "l", "sold": false }
      ],
      "6": [
        { "idx": 0, "col": "a", "sold": false },
        { "idx": 1, "col": "b", "sold": false },
        { "idx": 2, "col": "c", "sold": false },
        { "idx": 3, "col": "d", "sold": false },
        { "idx": 4, "col": "e", "sold": false },
        { "idx": 5, "col": "f", "sold": false },
        { "idx": 6, "col": "g", "sold": false },
        { "idx": 7, "col": "h", "sold": false },
        { "idx": 8, "col": "i", "sold": false },
        { "idx": 9, "col": "j", "sold": false },
        { "idx": 10, "col": "k", "sold": false },
        { "idx": 11, "col": "l", "sold": false }
      ]
    }
  }
]
